[package]
name = 'AdAuction'
version = '1.0.0'

[addresses]
AdAuction = '_'

[dev-addresses]
AdAuction = '0x2'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
